ESPMegaWebServer
FRAM* ESPMegaWebServer::fram
char ESPMegaWebServer::webUsername[32][32]
char ESPMegaWebServer::webPassword[32][32]
AsyncWebServer* ESPMegaWebServer::server
uint16_t ESPMegaWebServer::port
ESPMegaIoT* ESPMegaWebServer::iot
AsyncCallbackJsonWebHandler* ESPMegaWebServer::saveConfigHandler
ESPMegaWebServer::ESPMegaWebServer(uint16_t port, ESPMegaIoT *iot)
Construct a new ESPMegaWebServer::ESPMegaWebServer objecy.
Although you can instantiate this class directly, it is recommended to use the ESPMegaPRO.webServer object instead. port The TCP port to listen on iot A pointer to the ESPMegaIoT object
ESPMegaWebServer::~ESPMegaWebServer()
Destroy the ESPMegaWebServer::ESPMegaWebServer object.
void ESPMegaWebServer::begin()
Start the web server.
This method starts the web server and registers the necessary handlers. This method should be called after the ESPMegaIoT object has been initialized. This method is automatically called if you use ESPMegaPRO::enableWebServer()
References loadCredentialsFromFRAM.
Referenced by ESPMegaPRO::enableWebServer.
void ESPMegaWebServer::loop()
The loop function for the web server.
This method is not used by the ESPMegaWebServer class as of now.
Referenced by ESPMegaPRO::loop.
void ESPMegaWebServer::resetCredentials()
Reset web username and password to default.
This method resets the web server credentials to the default username and password. The default username and password is both "admin"
References saveCredentialsToFRAM.
Referenced by loadCredentialsFromFRAM.
char * ESPMegaWebServer::getWebUsername()
Get the web username.
The returned pointer should not be freed or modified. The web username
char * ESPMegaWebServer::getWebPassword()
Get the web password.
The returned pointer should not be freed or modified. The web password
void ESPMegaWebServer::setWebUsername(const char *username)
Set the web username.
username The new web username
void ESPMegaWebServer::setWebPassword(const char *password)
Set the web password.
password The new web password
void ESPMegaWebServer::bindFRAM(FRAM *fram)
Bind the FRAM object to the web server.
This method binds the FRAM object to the web server so that the web server can read and write credentials to the FRAM. The FRAM object must be bound to the web server before calling ESPMegaWebServer::begin() This class takes 64 bytes of FRAM starting from address 301, however address 301-400 is reserved for it. fram A pointer to the FRAM object
Referenced by ESPMegaPRO::enableWebServer.
void ESPMegaWebServer::loadCredentialsFromFRAM()
Load web username and password from FRAM.
This method loads the web server credentials from the FRAM. This method is automatically called by ESPMegaWebServer::begin()
References resetCredentials.
Referenced by begin.
void ESPMegaWebServer::saveCredentialsToFRAM()
Save web username and password to FRAM.
This method saves the web server credentials to the FRAM.
Referenced by resetCredentials.
AsyncWebServer * ESPMegaWebServer::getServer()
Get the AsyncWebServer object.
The AsyncWebServer object
void ESPMegaWebServer::dashboardHandler(AsyncWebServerRequest *request)
Handle HTTP requests to the dashboard (/) page.
request The AsyncWebServerRequest object
String ESPMegaWebServer::dashboardProcessor(const String &var)
Replace placeholders in the dashboard HTML with values.
var The placeholder name The value to replace the placeholder with
void ESPMegaWebServer::configHandler(AsyncWebServerRequest *request)
Handle HTTP requests to the config (/config) page.
request The AsyncWebServerRequest object
String ESPMegaWebServer::configProcessor(const String &var)
Replace placeholders in the config HTML with values.
var The placeholder name The value to replace the placeholder with
void ESPMegaWebServer::saveConfigJSONHandler(AsyncWebServerRequest *request, JsonVariant &json)
Handle JSON POST requests to the save_config (/save_config) page.
request The AsyncWebServerRequest object json The JSON object representing the request body
void ESPMegaWebServer::otaRequestHandler(AsyncWebServerRequest *request)
Handle HTTP requests to the OTA update (/ota_update) page.
request The AsyncWebServerRequest object
void ESPMegaWebServer::otaUploadHandler(AsyncWebServerRequest *request, String filename, size_t index, uint8_t *data, size_t len, bool final)
Handle HTTP upload session to the OTA update (/ota_update) page.
request The AsyncWebServerRequest object filename The filename of the firmware index The index of the firmware data The firmware data len The length of the firmware data final Whether this is the final chunk of firmware
void ESPMegaWebServer::restAPIHandler(AsyncWebServerRequest *request)