ClimateCard
DHTNEW* ClimateCard::dht
DS18B20* ClimateCard::ds18b20
uint8_t ClimateCard::callbacks_handler_count
uint8_t ClimateCard::sensor_callbacks_handler_count
std::map<uint8_t,std::function<void(uint8_t, uint8_t, uint8_t)> > ClimateCard::callbacks
std::map<uint8_t,std::function<void(float, float)> > ClimateCard::sensor_callbacks
uint8_t ClimateCard::ir_pin
AirConditioner ClimateCard::ac
ClimateCardData ClimateCard::state
uint8_t ClimateCard::sensor_type
uint8_t ClimateCard::sensor_pin
float ClimateCard::humidity
float ClimateCard::room_temperature
FRAM* ClimateCard::fram
uint16_t ClimateCard::fram_address
bool ClimateCard::fram_auto_save
ClimateCard::ClimateCard(uint8_t ir_pin, AirConditioner ac, uint8_t sensor_type, uint8_t sensor_pin)
Construct a new ClimateCard object.
ir_pin The GPIO pin number of the IR transmitter. ac The AirConditioner object that represents the air conditioner. sensor_type The type of the sensor connected to the card. sensor_pin The GPIO pin number of the sensor.
References ClimateCardData::ac_fan_speed, ClimateCardData::ac_mode, ClimateCardData::ac_temperature.
ClimateCard::ClimateCard(uint8_t ir_pin, AirConditioner ac)
Construct a new ClimateCard object.
ir_pin The GPIO pin number of the IR transmitter. ac The AirConditioner object that represents the air conditioner. This constructor can be used when no sensor is connected to the card.
ClimateCard::~ClimateCard()
The destructor of the ClimateCard class.
bool ClimateCard::begin()
Initialize the ClimateCard object.
true if initialization was successful. false if initialization failed.
void ClimateCard::loop()
Loop function of the ClimateCard class.
When this card is installed in an ESPMega, this function is called automatically by the ESPMega class.
void ClimateCard::bindFRAM(FRAM *fram, uint16_t fram_address)
bind FRAM memory to the ClimateCard object at the specified address.
This function must be called before calling loadStateFromFRAM() or saveStateToFRAM(). This card takes up 3 bytes of FRAM memory. fram The FRAM object. fram_address The starting address of the card in FRAM memory.
void ClimateCard::setFRAMAutoSave(bool autoSave)
Set whether the state should be automatically saved to FRAM memory.
This function has no effect if bindFRAM() has not been called. autoSave Whether the state should be automatically saved to FRAM memory.
void ClimateCard::saveStateToFRAM()
Save the state to FRAM memory.
This function has no effect if bindFRAM() has not been called.
References ClimateCardData::ac_fan_speed, ClimateCardData::ac_mode, ClimateCardData::ac_temperature.
Referenced by setFanSpeed, setMode, setTemperature.
void ClimateCard::loadStateFromFRAM()
Load the state from FRAM memory.
This function has no effect if bindFRAM() has not been called.
References ClimateCardData::ac_fan_speed, ClimateCardData::ac_mode, ClimateCardData::ac_temperature, AirConditioner::fan_speeds, AirConditioner::max_temperature, AirConditioner::min_temperature, AirConditioner::modes.
void ClimateCard::setTemperature(uint8_t temperature)
Set the temperature of the air conditioner.
temperature The temperature to set. If the temperature is out of range, it will be set to its respective maximum or minimum.
References ClimateCardData::ac_temperature, AirConditioner::max_temperature, AirConditioner::min_temperature, saveStateToFRAM.
uint8_t ClimateCard::getTemperature()
Get the temperature of the air conditioner.
The temperature of the air conditioner.
References ClimateCardData::ac_temperature.
Referenced by ClimateIoT::publishClimateTemperature.
void ClimateCard::setMode(uint8_t mode)
Set the mode of the air conditioner.
If the mode is out of range, it will be set to 0. mode The mode to set.
References ClimateCardData::ac_mode, AirConditioner::modes, saveStateToFRAM.
Referenced by setModeByName.
void ClimateCard::setModeByName(const char *mode_name)
Set mode by name.
mode_name The name of the mode to set. If the mode is not found, the function will not do anything.
References AirConditioner::mode_names, AirConditioner::modes, setMode.
uint8_t ClimateCard::getMode()
Get the mode of the air conditioner.
The mode of the air conditioner.
References ClimateCardData::ac_mode.
char * ClimateCard::getModeName()
Get the name of the current mode.
The name of the current mode.
References ClimateCardData::ac_mode, AirConditioner::mode_names.
Referenced by ClimateIoT::publishClimateMode.
void ClimateCard::setFanSpeed(uint8_t fan_speed)
Set the fan speed of the air conditioner.
If the fan speed is out of range, it will be set to 0. fan_speed The fan speed to set.
References ClimateCardData::ac_fan_speed, AirConditioner::fan_speeds, saveStateToFRAM.
Referenced by setFanSpeedByName.
void ClimateCard::setFanSpeedByName(const char *fan_speed_name)
Set fan speed by name.
fan_speed_name The name of the fan speed to set. If the fan speed is not found, the function will not do anything.
References AirConditioner::fan_speed_names, AirConditioner::fan_speeds, setFanSpeed.
uint8_t ClimateCard::getFanSpeed()
Get the fan speed of the air conditioner.
The fan speed of the air conditioner.
References ClimateCardData::ac_fan_speed.
char * ClimateCard::getFanSpeedName()
Get the name of the current fan speed.
The name of the current fan speed.
References ClimateCardData::ac_fan_speed, AirConditioner::fan_speed_names.
Referenced by ClimateIoT::publishClimateFanSpeed.
float ClimateCard::getRoomTemperature()
Get the room temperature in degrees Celsius.
The room temperature.
Referenced by ClimateIoT::publishRoomTemperature.
float ClimateCard::getHumidity()
Get the humidity in percent.
The humidity.
Referenced by ClimateIoT::publishHumidity.
uint8_t ClimateCard::getSensorType()
Get the type of the sensor connected to the card.
The type of the sensor connected to the card.
Referenced by ClimateIoT::publishHumidity, ClimateIoT::publishRoomTemperature.
uint8_t ClimateCard::registerChangeCallback(std::function< void(uint8_t, uint8_t, uint8_t)> callback)
Register a callback function that will be called when the state of the air conditioner changes.
callback The callback function to register. uint8_t The handler of the callback function.
Referenced by InternalDisplay::bindClimateCard.
uint8_t ClimateCard::registerSensorCallback(std::function< void(float, float)> callback)
Register a callback function that will be called when the sensor data changes.
callback The callback function to register. The handler of the callback function
void ClimateCard::unregisterChangeCallback(uint8_t handler)
Unregister a callback function.
handler The handler of the callback function to unregister.
Referenced by InternalDisplay::unbindClimateCard.
void ClimateCard::unregisterSensorCallback(uint8_t handler)
Unregister a sensor callback function.
handler The handler of the callback function to unregister.
uint8_t ClimateCard::getType()
Get the type of the card.
The handler of the callback function.
void ClimateCard::updateSensor()
update environmental sensor data.
This function is called automatically by the loop() function. This function has no effect if no sensor is connected to the card. This function also calls the sensor callbacks.
void ClimateCard::updateAirConditioner()
Update the air conditioner state to match the state of the card.
This function is not working yet.
uint16_t* ClimateCard::getIrIndex(uint8_t mode, uint8_t fan_speed, uint8_t temperature)