DigitalInputCard
PCF8574 DigitalInputCard::inputBankA
PCF8574 DigitalInputCard::inputBankB
uint8_t DigitalInputCard::address_a
uint8_t DigitalInputCard::address_b
uint8_t DigitalInputCard::inputBufferA
uint8_t DigitalInputCard::inputBufferB
uint8_t DigitalInputCard::previousInputBufferA
uint8_t DigitalInputCard::previousInputBufferB
uint32_t DigitalInputCard::debounceTime[16][16]
uint32_t DigitalInputCard::lastDebounceTime[16][16]
uint8_t DigitalInputCard::pinMap[16][16]
uint8_t DigitalInputCard::virtualPinMap[16][16]
uint8_t DigitalInputCard::callbacks_handler_index
std::map<uint8_t, std::function<void(uint8_t, bool)> > DigitalInputCard::callbacks
DigitalInputCard::DigitalInputCard(uint8_t address_a, uint8_t address_b)
Create a new Digital Input Card object with the specified address.
If you are using the ESPMegaI/O board, you should use the dip switch constructor address_a The ESPMegaI/O address of bank A address_b The ESPMegaI/O address of bank B
DigitalInputCard::DigitalInputCard(bool bit0, bool bit1, bool bit2, bool bit3, bool bit4, bool bit5)
Create a new Digital Input Card object with the specified position on the dip switch.
The bit 0 are at the left of the dip switch There are 6 switches on the dip switch, 3 for bank A and 3 for bank B, They should be unique for each bank accross all the cards bit0 The position of the first switch on the dip switch bit1 The position of the second switch on the dip switch bit2 The position of the third switch on the dip switch bit3 The position of the fourth switch on the dip switch bit4 The position of the fifth switch on the dip switch bit5 The position of the sixth switch on the dip switch
bool DigitalInputCard::begin()
Initialize the Digital Input Card.
True if the initialization is successful, false otherwise
bool DigitalInputCard::digitalRead(uint8_t pin)
Read the input from the specified pin, always refresh the input buffers.
pin The pin to read from True if the pin is HIGH, false if the pin is LOW
Referenced by DigitalInputIoT::publishDigitalInput.
bool DigitalInputCard::digitalRead(uint8_t pin, bool refresh)
Read the input from the specified pin, also refresh the input buffers if refresh is true.
pin The pin to read from refresh If true, the input buffers will be refreshed before reading the pin True if the pin is HIGH, false if the pin is LOW
void DigitalInputCard::loop()
A loop to refresh the input buffers and check for pin changes.
Although this function can be called in the main loop, it is recommended install the card in ESPMega to automatically manage the loop
Referenced by ESPMegaPRO::loop.
uint8_t DigitalInputCard::getInputBufferA()
Get the input buffer for bank A (the first 8 pins)
The input buffer for bank A where the first bit is the first pin and the last bit is the last pin
uint8_t DigitalInputCard::getInputBufferB()
Get the input buffer for bank B (the last 8 pins)
The input buffer for bank B where the first bit is the first pin and the last bit is the last pin
void DigitalInputCard::setDebounceTime(uint8_t pin, uint32_t debounceTime)
Set the debounce time for the specified pin.
Debounce is the time in milliseconds that the pin should be stable before the callback function is called This is useful to prevent false triggers when the input is noisy An example of this is when the input is connected to a mechanical switch pin The pin to set the debounce time for debounceTime The debounce time in milliseconds
uint8_t DigitalInputCard::registerCallback(std::function< void(uint8_t, bool)> callback)
Register a callback function to be called when a pin changes.
callback The callback function to be called The handler of the callback function
Referenced by InternalDisplay::bindInputCard.
void DigitalInputCard::unregisterCallback(uint8_t handler)
Unregister a callback function.
handler The handler of the callback function to unregister
Referenced by InternalDisplay::unbindInputCard.
void DigitalInputCard::loadPinMap(uint8_t pinMap[16])
Load the pin map for the card.
A pin map is an array of 16 elements that maps the physical pins to virtual pins The virtual pins are the pins that are used in the callback functions and are used for all the functions in this class The physical pins are the pins on the Input IC, This can be found on the schematic of the ESPMegaI/O board This function is useful if you want to change the number identification of the pins to match your project needs pinMap The pin map to load
Referenced by ESPMegaPRO::begin.
uint8_t DigitalInputCard::getType()
Get the type of the card.
The type of the card
void DigitalInputCard::refreshInputBankA()
Read the input state from the input ic and store it in the input buffer for bank A.
void DigitalInputCard::refreshInputBankB()
Read the input state from the input ic and store it in the input buffer for bank B.
void DigitalInputCard::handlePinChange(int pin, uint8_t &currentBuffer, uint8_t &previousBuffer)
Check if the specified pin changed since the last call to this function.
This function compares the current input buffer with the previous input buffer to detect changes pin The pin to check currentBuffer The current input buffer previousBuffer The previous input buffer