ESPMegaPRO
FRAM ESPMegaPRO::fram
DigitalInputCard ESPMegaPRO::inputs
DigitalOutputCard ESPMegaPRO::outputs
InternalDisplay* ESPMegaPRO::display
ESPMegaIoT* ESPMegaPRO::iot
ESPMegaWebServer* ESPMegaPRO::webServer
bool ESPMegaPRO::iotEnabled
bool ESPMegaPRO::internalDisplayEnabled
bool ESPMegaPRO::webServerEnabled
ExpansionCard* ESPMegaPRO::cards[255][255]
bool ESPMegaPRO::cardInstalled[255][255]
uint8_t ESPMegaPRO::cardCount
ESPMegaPRO::ESPMegaPRO()
Create a new ESPMegaPRO object.
Only one ESPMegaPRO object can be created, creating more than one will result in undefined behavior
bool ESPMegaPRO::begin()
Initializes the ESPMegaPRO object.
This function initializes the ESPMegaPRO object and all of its components. It also initializes the built-in Digital Input and Digital Output cards. True if the initialization is successful, false otherwise.
References DigitalOutputCard::bindFRAM, installCard, DigitalOutputCard::loadFromFRAM, DigitalInputCard::loadPinMap, DigitalOutputCard::setAutoSaveToFRAM.
void ESPMegaPRO::loop()
The main loop for the ESPMegaPRO object.
This function must be called in the main loop of the program. It will call the loop() function of all installed expansion cards, the ESPMegaIoT module, and the internal display.
References DigitalInputCard::loop, DigitalOutputCard::loop, ESPMegaIoT::loop, ESPMegaWebServer::loop, InternalDisplay::loop.
bool ESPMegaPRO::installCard(uint8_t slot, ExpansionCard *card)
Installs an expansion card to the specified slot.
This function automatically initializes the expansion card. slot The slot to install the card to. card Pointer to the ExpansionCard object. True if the installation is successful, false otherwise.
Referenced by begin.
bool ESPMegaPRO::updateTimeFromNTP()
Updates the internal RTC from NTP.
Network must be connected before calling this function (see ESPMegaPRO.ESPMegaIoT::connectNetwork()). True if the update is successful, false otherwise.
References getTime, setTime.
void ESPMegaPRO::enableIotModule()
Enables, Instanitates, and Initializes the ESPMegaIoT module.
This function must be called before using the ESPMegaIoT module.
References ESPMegaIoT::bindFRAM, ESPMegaIoT::intr_begin.
void ESPMegaPRO::enableInternalDisplay(HardwareSerial *serial)
Enables, Instanitates, and Initializes the internal display.
&Serial is used for the internal display on ESPMegaPRO R3. This function can only be called if the ESPMegaIoT module is enabled. This function must be called before using the internal display. serial Pointer to the HardwareSerial object to use for the internal display (Serial for ESPMegaPRO R3).
References InternalDisplay::begin, InternalDisplay::bindInputCard, InternalDisplay::bindOutputCard, getTime.
void ESPMegaPRO::enableWebServer(uint16_t port)
Enables the internal web server.
This function can only be called if the ESPMegaIoT module is enabled. This function can only be called once. port The port to use for the web server.
References ESPMegaWebServer::begin, ESPMegaWebServer::bindFRAM.
rtctime_t ESPMegaPRO::getTime()
Gets the current time from the internal RTC.
The current time as a rtctime_t struct.
Referenced by enableInternalDisplay, updateTimeFromNTP.
void ESPMegaPRO::dumpFRAMtoSerial(uint16_t start, uint16_t end)
Dumps the contents of the internal FRAM to the serial port.
start The starting address. end The ending address.
void ESPMegaPRO::dumpFRAMtoSerialASCII(uint16_t start, uint16_t end)
Dumps the contents of the internal FRAM to the serial port in ASCII.
start The starting address. end The ending address.
void ESPMegaPRO::setTime(int hours, int minutes, int seconds, int day, int month, int year)
Sets the current time of the internal RTC.
hours The hours. minutes The minutes. seconds The seconds. day The day. month The month. year The year.
Referenced by updateTimeFromNTP.
ExpansionCard * ESPMegaPRO::getCard(uint8_t slot)
Gets the expansion card installed at the specified slot.
slot The slot to get the card from. Pointer to the ExpansionCard object, or nullptr if no card is installed at the specified slot.