InternalDisplay
uint8_t InternalDisplay::bindedInputCardCallbackHandler
uint8_t InternalDisplay::bindedOutputCardCallbackHandler
uint8_t InternalDisplay::bindedClimateCardCallbackHandler
uint8_t InternalDisplay::bindedClimateCardSensorCallbackHandler
DigitalInputCard* InternalDisplay::inputCard
DigitalOutputCard* InternalDisplay::outputCard
ClimateCard* InternalDisplay::climateCard
uint8_t InternalDisplay::pmwAdjustmentPin
MqttConfig* InternalDisplay::mqttConfig
NetworkConfig* InternalDisplay::networkConfig
ESPMegaIoT* InternalDisplay::iot
std::function<rtctime_t()> InternalDisplay::getRtcTime
InternalDisplay::InternalDisplay(HardwareSerial *displayAdapter)
Create a new Internal Display object.
displayAdapter The HardwareSerial object that is connected to the display
void InternalDisplay::begin(ESPMegaIoT *iot, std::function< rtctime_t()> getRtcTime)
Initialize the Internal Display.
You should not call this function directly, instead use ESPMegaIoT::enableInternalDisplay() iot The ESPMegaIoT object getRtcTime A function that returns the current time
References ESPMegaIoT::getMqttConfig, ESPMegaIoT::getNetworkConfig, ESPMegaDisplay::jumpToPage, ESPMegaDisplay::registerPageChangeCallback, ESPMegaDisplay::registerTouchCallback, ESPMegaDisplay::reset.
Referenced by ESPMegaPRO::enableInternalDisplay.
void InternalDisplay::loop()
The main loop of the Internal Display.
You should not call this function directly, instead use ESPMega::loop()
References ESPMegaIoT::networkConnected, ESPMegaDisplay::recieveSerialCommand.
Referenced by ESPMegaPRO::loop.
void InternalDisplay::bindInputCard(DigitalInputCard *inputCard)
Set the input card to be be shown on the input page.
inputCard The input card object to be shown
References DigitalInputCard::registerCallback, unbindInputCard.
Referenced by ESPMegaPRO::enableInternalDisplay.
void InternalDisplay::bindOutputCard(DigitalOutputCard *outputCard)
Set the output card to be be shown on the output page.
outputCard The output card object to be shown
References DigitalOutputCard::registerChangeCallback, unbindOutputCard.
Referenced by ESPMegaPRO::enableInternalDisplay.
void InternalDisplay::bindClimateCard(ClimateCard *climateCard)
Set the climate card to be be shown on the AC page.
This assume that your ClimeateCard has the mode and fan speed names in the following order: mode: [off, fan_only, cool] fan_speed: [auto, low, medium, high] climateCard The climate card object to be shown
References ClimateCard::registerChangeCallback, unbindClimateCard.
void InternalDisplay::unbindInputCard()
Unbind the input card from the display.
References DigitalInputCard::unregisterCallback.
Referenced by bindInputCard.
void InternalDisplay::unbindOutputCard()
Unbind the output card from the display.
References DigitalOutputCard::unregisterChangeCallback.
Referenced by bindOutputCard.
void InternalDisplay::unbindClimateCard()
Unbind the climate card from the display.
References ClimateCard::unregisterChangeCallback.
Referenced by bindClimateCard.
void InternalDisplay::handleInputStateChange(uint8_t pin, bool state)
Update the display in response to a change in the input state.
pin The pin that changed state The new state of the pin
void InternalDisplay::handlePwmStateChange(uint8_t pin, bool state, uint16_t value)
Update the display in response to a change in the PWM state.
pin The pin that changed state The new state of the pin value The new value of the pin
void InternalDisplay::handlePageChange(uint8_t page)
Update the display in response to page change.
page The new page
void InternalDisplay::setOutputBar(uint8_t pin, uint16_t value)
Set the PWM status output bar value (Fullness of the bar)
pin The pin of the PWM value The value of the PWM (0 - 4095)
void InternalDisplay::setOutputStateColor(uint8_t pin, bool state)
Set the PWM status output bar color to match the PWM state.
pin The pin of the PWM state The state of the PWM
void InternalDisplay::setInputMarker(uint8_t pin, bool state)
Set Input Marker to match the input state.
pin The pin of the input state The state of the input
void InternalDisplay::handleACStateChange(uint8_t mode, uint8_t fan_speed, uint8_t temperature)
Handle the AC state change.
This function is registered as a callback to the ClimateCard mode The new mode fan_speed The new fan speed temperature The new temperature
void InternalDisplay::saveNetworkConfig()
Save the network config to the FRAM.
void InternalDisplay::saveMQTTConfig()
Save the MQTT config to the FRAM.
void InternalDisplay::updateStatusIcons(bool networkStatus, bool mqttStatus)
Update the status icons on the Internal Display's top bar.
networkStatus The network status mqttStatus The MQTT status
void InternalDisplay::updateClock()
Update the clock on the Internal Display's top bar.
void InternalDisplay::refreshPage()
Send data to display element on the current page.
void InternalDisplay::refreshPage(uint8_t page)
Send data to display element on the specified page.
The current page must be the specified page page The page to refresh
void InternalDisplay::refreshDashboard()
Send data to display element on the dashboard page.
void InternalDisplay::refreshInput()
Send data to display element on the input page.
void InternalDisplay::refreshOutput()
Send data to display element on the output page.
void InternalDisplay::refreshAC()
Send data to display element on the AC page.
void InternalDisplay::refreshPWMAdjustment()
Send data to display element on the PWM Adjustment page.
void InternalDisplay::refreshPWMAdjustmentSlider()
Send the PWM value to the display on the PWM Adjustment page.
void InternalDisplay::refreshPWMAdjustmentState()
Send the PWM state to the display on the PWM Adjustment page.
void InternalDisplay::refreshPWMAdjustmentId()
Send the PWM pin id to the display on the PWM Adjustment page.
void InternalDisplay::refreshNetworkConfig()
Send data to display element on the network config page.
void InternalDisplay::refreshMQTTConfig()
Send data to display element on the mqtt config page.
void InternalDisplay::sendIpToDisplay(IPAddress ip)
Write an ip address to the display.
This function only writes the ip address to the display, you need to send the prefix and suffix yourself ip The ip address to send
void InternalDisplay::handleTouch(uint8_t page, uint8_t component, uint8_t type)
Handle the touch event on the display.
page The page that the touch event occured component The component that the touch event occured type The type of the touch event
void InternalDisplay::handlePWMAdjustmentTouch(uint8_t component, uint8_t type)
Handle the touch event on the PWM Adjustment page.
type The type of the touch event component The component that the touch event occured
void InternalDisplay::handleACTouch(uint8_t component, uint8_t type)
Handle the touch event on the AC page.
type The type of the touch event component The component that the touch event occured