ClimateIoT
ClimateCard* ClimateIoT::card
ClimateIoT::ClimateIoT()
ClimateIoT::~ClimateIoT()
Destructor for the ClimateIoT class.
bool ClimateIoT::begin(uint8_t card_id, ExpansionCard *card, PubSubClient *mqtt, char *base_topic)
Initializes the ClimateIoT component.
This function sets the MQTT client, base topic, card ID, and card pointer. It also registers the sensor and air conditioner update callbacks. card_id The ID of the expansion card. card A pointer to the ExpansionCard object. mqtt A pointer to the PubSubClient object. base_topic The base topic for MQTT communication. True if the initialization is successful, false otherwise.
References handleAirConditionerUpdate, handleSensorUpdate.
void ClimateIoT::handleMqttMessage(char *topic, char *payload)
Handles MQTT messages for the ClimateIoT component.
topic The trimmed topic of the MQTT message. payload The null-terminated payload of the MQTT message.
void ClimateIoT::publishClimate()
Publishes the climate data (temperature, mode, fan speed) to the MQTT broker.
References publishClimateFanSpeed, publishClimateMode, publishClimateTemperature.
Referenced by handleAirConditionerUpdate, handleStateChange, publishReport.
void ClimateIoT::publishClimateTemperature()
Publishes the temperature of the air conditioner to the MQTT broker.
References ClimateCard::getTemperature.
Referenced by publishClimate.
void ClimateIoT::publishClimateMode()
Publishes the mode of the air conditioner to the MQTT broker.
References ClimateCard::getModeName.
Referenced by publishClimate.
void ClimateIoT::publishClimateFanSpeed()
Publishes the fan speed of the air conditioner to the MQTT broker.
References ClimateCard::getFanSpeedName.
Referenced by publishClimate.
void ClimateIoT::publishSensor()
Publishes the temperature and humidity of the room to the MQTT broker.
References publishHumidity, publishRoomTemperature.
Referenced by handleSensorUpdate, publishReport.
void ClimateIoT::publishRoomTemperature()
Publishes the room temperature to the MQTT broker.
References ClimateCard::getRoomTemperature, ClimateCard::getSensorType.
Referenced by publishSensor.
void ClimateIoT::publishHumidity()
Publishes the humidity of the room to the MQTT broker.
References ClimateCard::getHumidity, ClimateCard::getSensorType.
Referenced by publishSensor.
void ClimateIoT::handleStateChange(uint8_t temperature, uint8_t mode, uint8_t fan_speed)
Handle Air Conditioner state change.
This function is called by the underlying ClimateCard object and is not meant to be called manually. temperature Temperature of the air conditioner mode Mode of the air conditioner fan_speed Fan speed of the air conditioner
References publishClimate.
void ClimateIoT::handleSensorUpdate(float temperature, float humidity)
This function is a callback function registered with the Climate card to be called when the sensor data is updated.
temperature The room temperature. humidity The room humidity. The temperature and humidity are not used in this function but are required by the ClimateCard class to match the signature of the callback function.
References publishSensor.
Referenced by begin.
void ClimateIoT::handleAirConditionerUpdate(uint8_t mode, uint8_t fan_speed, uint8_t temperature)
This function is a callback function registered with the Climate card to be called when the air conditioner state is updated.
mode The mode of the air conditioner. fan_speed The fan speed of the air conditioner. temperature The temperature of the air conditioner.
References publishClimate.
Referenced by begin.
void ClimateIoT::publishReport()
Publishes the climate and sensor data to the MQTT broker.
References publishClimate, publishSensor.
void ClimateIoT::subscribe()
Subscribes to MQTT topics.
void ClimateIoT::loop()
The loop function for the ClimateIoT component.
This function does nothing.
uint8_t ClimateIoT::getType()
Returns the type of the expansion card.
The type of the expansion card.
bool ClimateIoT::processSetTemperatureMessage(char *topic, char *payload, uint8_t topic_length)
Processes the set temperature MQTT message.
topic The trimmed topic of the MQTT message. payload The null-terminated payload of the MQTT message. topic_length The length of the topic. True if the message is processed, false otherwise.
bool ClimateIoT::processSetModeMessage(char *topic, char *payload, uint8_t topic_length)
Processes the set mode MQTT message.
topic The trimmed topic of the MQTT message. payload The null-terminated payload of the MQTT message. topic_length The length of the topic. True if the message is processed, false otherwise.
bool ClimateIoT::processSetFanSpeedMessage(char *topic, char *payload, uint8_t topic_length)
Processes the set fan speed MQTT message.
topic The trimmed topic of the MQTT message. payload The null-terminated payload of the MQTT message. topic_length The length of the topic. True if the message is processed, false otherwise.
bool ClimateIoT::processRequestStateMessage(char *topic, char *payload, uint8_t topic_length)
Processes the request state MQTT message.
topic The trimmed topic of the MQTT message. payload The null-terminated payload of the MQTT message. topic_length The length of the topic. True if the message is processed, false otherwise.