ESPMegaDisplay
uint8_t ESPMegaDisplay::currentPage
uint8_t ESPMegaDisplay::rx_buffer_index
char ESPMegaDisplay::rx_buffer[256][256]
char ESPMegaDisplay::tx_buffer[256][256]
HardwareSerial* ESPMegaDisplay::displayAdapter
std::map<uint16_t, std::function<void(uint8_t, uint8_t, uint8_t)> > ESPMegaDisplay::touch_callbacks
std::map<uint16_t, std::function<void(uint8_t)> > ESPMegaDisplay::page_change_callbacks
ESPMegaDisplay::ESPMegaDisplay(HardwareSerial *displayAdapter)
Constructor for the ESPMegaDisplay class.
displayAdapter The serial adapter connected to the display.
void ESPMegaDisplay::begin()
Initializes the display.
References reset.
void ESPMegaDisplay::loop()
The main loop function of the display.
References recieveSerialCommand.
void ESPMegaDisplay::reset()
Restarts the display.
References sendStopBytes.
Referenced by begin, InternalDisplay::begin.
void ESPMegaDisplay::setBrightness(int value)
Sets the brightness of the display.
value The brightness value.
References sendStopBytes.
void ESPMegaDisplay::setVolume(int value)
Sets the volume of the display.
value The volume value.
References sendStopBytes.
void ESPMegaDisplay::jumpToPage(int page)
Jumps to the specified page on the display.
page The page number to jump to.
References sendStopBytes.
Referenced by InternalDisplay::begin.
void ESPMegaDisplay::setString(const char *component, const char *value)
Sets the value of a string component on the display.
component The component name. value The value to set.
References sendStopBytes.
void ESPMegaDisplay::setNumber(const char *component, int value)
Sets the value of a number component on the display.
component The component name. value The value to set.
References sendStopBytes.
const char * ESPMegaDisplay::getString(const char *component)
Gets the value of a string component from the display.
This function is blocking. If the display does not respond or is not connected, this function will block for up to DISPLAY_FETCH_RETRY_COUNT * DISPLAY_FETCH_TIMEOUT milliseconds. component The component name. The value of the string component. The returned char array must be freed after use.
References sendStopBytes, waitForValidPayload.
bool ESPMegaDisplay::getStringToBuffer(const char *component, char *buffer, uint8_t buffer_size)
Gets the value of a number component from the display and stores it in a buffer.
This function is blocking. If the display does not respond or is not connected, this function will block for up to DISPLAY_FETCH_RETRY_COUNT * DISPLAY_FETCH_TIMEOUT milliseconds. component The component name. buffer The buffer to store the value. buffer_size The size of the buffer. True if the value is successfully stored in the buffer, false otherwise.
References sendStopBytes, waitForValidPayload.
uint32_t ESPMegaDisplay::getNumber(const char *component)
Gets the value of a number component from the display.
This function is blocking. If the display does not respond or is not connected, this function will block for up to DISPLAY_FETCH_RETRY_COUNT * DISPLAY_FETCH_TIMEOUT milliseconds. component The component name. The value of the number component.
References sendStopBytes, waitForValidPayload.
uint16_t ESPMegaDisplay::registerTouchCallback(std::function< void(uint8_t, uint8_t, uint8_t)> callback)
Registers a callback function for touch events.
callback The callback function. The handle of the callback function.
Referenced by InternalDisplay::begin.
void ESPMegaDisplay::unregisterTouchCallback(uint16_t handle)
Unregisters a callback function for touch events.
handle The handle of the callback function.
uint16_t ESPMegaDisplay::registerPageChangeCallback(std::function< void(uint8_t)> callback)
Registers a callback function for page change events.
callback The callback function. The handle of the callback function.
Referenced by InternalDisplay::begin.
void ESPMegaDisplay::unregisterPageChangeCallback(uint16_t handle)
Unregisters a callback function for page change events.
handle The handle of the callback function.
bool ESPMegaDisplay::recieveSerialCommand()
Receives and processes serial commands from the display adapter.
True if data is received, false otherwise.
Referenced by loop, InternalDisplay::loop, waitForValidPayload.
bool ESPMegaDisplay::recieveSerialCommand(bool process)
Receives and processes serial commands from the display adapter.
process Flag indicating whether to process the received commands. True if data is received, false otherwise.
References processSerialCommand.
void ESPMegaDisplay::processSerialCommand()
Processes the received serial command.
This function interacts directly with the rx_buffer.
References payloadIsValid, processPageReportPayload, processTouchPayload.
Referenced by recieveSerialCommand.
void ESPMegaDisplay::processTouchPayload()
Processes the touch event payload.
This function interacts directly with the rx_buffer.
Referenced by processSerialCommand.
void ESPMegaDisplay::processPageReportPayload()
Processes the page report event payload.
This function interacts directly with the rx_buffer.
Referenced by processSerialCommand.
void ESPMegaDisplay::sendStopBytes()
Sends stop bytes to the display adapter.
Referenced by getNumber, getString, getStringToBuffer, jumpToPage, reset, sendCommand, setBrightness, setNumber, setString, setVolume.
void ESPMegaDisplay::sendCommand(char *command)
Sends a command to the display adapter.
command The command to send.
References sendStopBytes.
bool ESPMegaDisplay::payloadIsValid()
Checks if the received payload is valid.
True if the payload is valid, false otherwise.
Referenced by processSerialCommand, waitForValidPayload.
bool ESPMegaDisplay::waitForValidPayload(uint32_t timeout)
Waits for a valid payload from the display adapter.
timeout The timeout value in milliseconds. True if a valid payload is received, false otherwise.
References payloadIsValid, recieveSerialCommand.
Referenced by getNumber, getString, getStringToBuffer.