DigitalOutputIoT
bool DigitalOutputIoT::digital_outputs_publish_enabled
DigitalOutputCard* DigitalOutputIoT::card
char* DigitalOutputIoT::state_report_topic
char* DigitalOutputIoT::value_report_topic
uint8_t DigitalOutputIoT::set_state_length
uint8_t DigitalOutputIoT::set_value_length
uint8_t DigitalOutputIoT::state_length
uint8_t DigitalOutputIoT::value_length
uint8_t DigitalOutputIoT::request_state_length
uint8_t DigitalOutputIoT::publish_enable_length
DigitalOutputIoT::DigitalOutputIoT()
Create a new DigitalOutputIoT object.
DigitalOutputIoT::~DigitalOutputIoT()
Destroy the DigitalOutputIoT object.
bool DigitalOutputIoT::begin(uint8_t card_id, ExpansionCard *card, PubSubClient *mqtt, char *base_topic)
Initialize the DigitalOutputIoT object.
ALthough this function can be called inside the main program, it is recommended to use ESPMegaPRO::installCard() instead card_id The id of the card card The card object mqtt The PubSubClient object base_topic The base topic of the card True if the initialization is successful, false otherwise
References handleValueChange.
void DigitalOutputIoT::handleMqttMessage(char *topic, char *payload)
Handle the MQTT messages for the DigitalOutputIoT card.
topic The topic of the message payload The payload of the message
void DigitalOutputIoT::publishDigitalOutputs()
Publish the state of all digital outputs.
References publishDigitalOutput.
Referenced by publishReport.
void DigitalOutputIoT::publishDigitalOutput(uint8_t pin)
Publish the state and value of the specified digital output.
pin The pin to publish
References publishDigitalOutputState, publishDigitalOutputValue.
Referenced by handleValueChange, publishDigitalOutputs.
void DigitalOutputIoT::publishDigitalOutputState(uint8_t pin)
Publish the state of the specified digital output.
pin The pin to publish
References DigitalOutputCard::getState.
Referenced by publishDigitalOutput.
void DigitalOutputIoT::publishDigitalOutputValue(uint8_t pin)
Publish the value of the specified digital output.
pin The pin to publish
References DigitalOutputCard::getValue.
Referenced by publishDigitalOutput.
void DigitalOutputIoT::setDigitalOutputsPublishEnabled(bool enabled)
Enable/disable publishing of digital outputs.
enabled True to enable publishing, false to disable publishing
void DigitalOutputIoT::handleValueChange(uint8_t pin, bool state, uint16_t value)
Handle the value change of a pin.
This function is registered as a callback function with the DigitalOutputCard object pin The pin that changed state The new state of the pin value The new value of the pin
References publishDigitalOutput.
Referenced by begin.
void DigitalOutputIoT::publishReport()
Publish all digital outputs.
This function is called by the ESPMegaIoT object
References publishDigitalOutputs.
void DigitalOutputIoT::subscribe()
Subscribe to the MQTT topics used by the DigitalOutputIoT object.
void DigitalOutputIoT::loop()
The main loop for the DigitalOutputIoT object.
This function is not used, it is only here to implement the IoTComponent interface
uint8_t DigitalOutputIoT::getType()
Get the type of the IoT component.
The type of the IoT component
bool DigitalOutputIoT::processSetStateMessage(char *topic, char *payload, uint8_t topic_length)
Process a set state message.
topic The null terminated topic payload The null terminated payload topic_length The length of the topic True if the message is a set state message, false otherwise
bool DigitalOutputIoT::processSetValueMessage(char *topic, char *payload, uint8_t topic_length)
Process a set value message.
topic The null terminated topic payload The null terminated payload topic_length The length of the topic True if the message is a set value message, false otherwise
bool DigitalOutputIoT::processRequestStateMessage(char *topic, char *payload, uint8_t topic_length)
Process a request state message.
topic The null terminated topic payload The null terminated payload topic_length The length of the topic True if the message is a request state message, false otherwise