DigitalOutputCard
uint16_t DigitalOutputCard::framAddress
bool DigitalOutputCard::framBinded
bool DigitalOutputCard::framAutoSave
FRAM* DigitalOutputCard::fram
Adafruit_PWMServoDriver DigitalOutputCard::pwm
uint8_t DigitalOutputCard::address
bool DigitalOutputCard::state_buffer[16][16]
uint16_t DigitalOutputCard::value_buffer[16][16]
uint8_t DigitalOutputCard::callbacks_handler_index
std::map<uint8_t, std::function<void(uint8_t, bool, uint16_t)> > DigitalOutputCard::change_callbacks
uint8_t DigitalOutputCard::pinMap[16][16]
uint8_t DigitalOutputCard::virtualPinMap[16][16]
DigitalOutputCard::DigitalOutputCard(uint8_t address)
Create a new Digital Output Card object with the specified address.
If you are using the ESPMegaI/O board, you should use the dip switch constructor address The ESPMegaI/O address of the card
DigitalOutputCard::DigitalOutputCard(bool bit0, bool bit1, bool bit2, bool bit3, bool bit4)
Create a new Digital Output Card object with the specified position on the dip switch.
The bit 0 are at the left of the dip switch There are 5 switches on the dip switch, they should be unique accross all the cards bit0 The position of the first switch on the dip switch bit1 The position of the second switch on the dip switch bit2 The position of the third switch on the dip switch bit3 The position of the fourth switch on the dip switch bit4 The position of the fifth switch on the dip switch
bool DigitalOutputCard::begin()
Initialize the Digital Output Card.
Although this function can be called inside the main program, it is recommended to use ESPMegaPRO::installCard() instead True if the initialization is successful, false otherwise
void DigitalOutputCard::loop()
The main loop for the Digital Output Card object.
This function is not used, it is only here to implement the ExpansionCard interface
Referenced by ESPMegaPRO::loop.
void DigitalOutputCard::digitalWrite(uint8_t pin, bool state)
Write a digtal LOW or HIGH to the specified pin.
This function set both the state and the pwm value of the pin pin The pin to set the state state The logic level to set the pin to
References savePinValueToFRAM, saveStateToFRAM.
void DigitalOutputCard::analogWrite(uint8_t pin, uint16_t value)
Write a pwm value to the specified pin.
This function set both the state and the pwm value of the pin pin The pin to set the pwm value value The pwm value to set
References savePinValueToFRAM, saveStateToFRAM.
void DigitalOutputCard::setState(uint8_t pin, bool state)
Set the state of the specified pin.
pin The pin to set the state state The state of the pin
References saveStateToFRAM.
void DigitalOutputCard::setValue(uint8_t pin, uint16_t value)
Set the pwm value of the specified pin.
pin The pin to set the pwm value value The pwm value to set
References savePinValueToFRAM.
Referenced by loadFromFRAM.
bool DigitalOutputCard::getState(uint8_t pin)
Get the state of the specified pin.
pin The pin to get the state The state of the pin
Referenced by DigitalOutputIoT::publishDigitalOutputState.
uint16_t DigitalOutputCard::getValue(uint8_t pin)
Get the pwm value of the specified pin.
pin The pin to get the pwm value The pwm value of the pin
Referenced by DigitalOutputIoT::publishDigitalOutputValue.
uint8_t DigitalOutputCard::registerChangeCallback(std::function< void(uint8_t, bool, uint16_t)> callback)
Register a callback function for the specified pin.
callback The callback function to be called, the first parameter is the pin, the second parameter is the state, the third parameter is the pwm value The handler of the callback function
Referenced by InternalDisplay::bindOutputCard.
void DigitalOutputCard::unregisterChangeCallback(uint8_t handler)
Unregister a callback function.
handler The handler of the callback function to be unregistered
Referenced by InternalDisplay::unbindOutputCard.
void DigitalOutputCard::loadPinMap(uint8_t pinMap[16])
Load a pin map.
A pin map is an array of 16 elements that maps the physical pins to virtual pins The virtual pins are the pins that are used in the callback functions and are used for all the functions in this class The physical pins are the pins on the Output IC, This can be found on the schematic of the ESPMegaI/O board This function is useful if you want to change the number identification of the pins to match your project needs pinMap The pin map to load
void DigitalOutputCard::bindFRAM(FRAM *fram, uint16_t address)
Bind a FRAM to the card.
The Output Card use 34 bytes of FRAM If the fram range overlap with another card, undefined behavior will occur fram The FRAM to bind address The address of the card in the FRAM
Referenced by ESPMegaPRO::begin.
void DigitalOutputCard::saveToFRAM()
Save the states and values of all the pins to the FRAM.
void DigitalOutputCard::loadFromFRAM()
Load the states and values of all the pins from the FRAM.
References setValue.
Referenced by ESPMegaPRO::begin.
void DigitalOutputCard::setAutoSaveToFRAM(bool autoSave)
Set the auto save to FRAM.
autoSave True to enable auto save, false to disable auto save
Referenced by ESPMegaPRO::begin.
void DigitalOutputCard::savePinValueToFRAM(uint8_t pin)
Save a single pin value to FRAM.
pin The pin to save
Referenced by analogWrite, digitalWrite, setValue.
void DigitalOutputCard::saveStateToFRAM()
Save the states of all the pins to FRAM.
Referenced by analogWrite, digitalWrite, setState.
void DigitalOutputCard::saveValueToFRAM()
uint8_t DigitalOutputCard::getType()
Get the type of the card.
The type of the card
uint16_t DigitalOutputCard::packStates()
Pack the states of all the pins into a 16 bit integer.
The packed states
void DigitalOutputCard::unpackStates(uint16_t states)
Unpack the states of all the pins from a 16 bit integer.
states The packed states