ESPMegaIoT
FRAM* ESPMegaIoT::fram
bool ESPMegaIoT::useWifi
bool ESPMegaIoT::WifiUseAuth
char ESPMegaIoT::ssid[32][32]
char ESPMegaIoT::password[32][32]
WiFiClient ESPMegaIoT::tcpClient
uint8_t ESPMegaIoT::mqtt_callbacks_handler_index
uint8_t ESPMegaIoT::mqtt_relative_callbacks_handler_index
uint8_t ESPMegaIoT::subscribe_callbacks_handler_index
std::map<uint8_t, std::function<void(char*, char*)> > ESPMegaIoT::mqtt_callbacks
std::map<uint8_t, std::function<void(char*, char*)> > ESPMegaIoT::mqtt_relative_callbacks
std::map<uint8_t, std::function<void(void)> > ESPMegaIoT::subscribe_callbacks
bool ESPMegaIoT::active
PubSubClient ESPMegaIoT::mqtt
IoTComponent* ESPMegaIoT::components[255][255]
char ESPMegaIoT::payload_buffer[200][200]
uint8_t ESPMegaIoT::base_topic_length
ExpansionCard** ESPMegaIoT::cards
bool ESPMegaIoT::mqtt_connected
NetworkConfig ESPMegaIoT::network_config
MqttConfig ESPMegaIoT::mqtt_config
ETHClass* ESPMegaIoT::ethernetIface
ESPMegaIoT::ESPMegaIoT()
Create a new ESPMegaIoT object.
You shold not create this object directly, Instead, you should use the ESPMegaPRO::iot object
ESPMegaIoT::~ESPMegaIoT()
Destroy the ESPMegaIoT object.
void ESPMegaIoT::intr_begin(ExpansionCard *cards[])
Begin the ESPMegaIoT object.
cards The array of ExpansionCard objects
Referenced by ESPMegaPRO::enableIotModule.
void ESPMegaIoT::loop()
The main loop for the ESPMegaIoT object.
Normally you should not call this function, Instead, you should call ESPMegaPRO::loop()
Referenced by ESPMegaPRO::loop.
void ESPMegaIoT::registerCard(uint8_t card_id)
Register an existing card for use with IoT.
This function registers an existing card for use with IoT The card should be installed using ESPMegaPRO::installCard() before calling this function card_id The id of the card
References MqttConfig::base_topic.
void ESPMegaIoT::unregisterCard(uint8_t card_id)
Unregister a card.
card_id The id of the card
void ESPMegaIoT::publishCard(uint8_t card_id)
Publish all cards's reports.
void ESPMegaIoT::publishRelative(char *topic, char *payload)
Publish a message relative to the base topic.
topic The topic to publish to payload The payload to publish
References MqttConfig::base_topic.
void ESPMegaIoT::subscribeRelative(char *topic)
Subscribe to a topic relative to the base topic.
topic The topic to subscribe to
References MqttConfig::base_topic.
void ESPMegaIoT::subscribe(char *topic)
Subscribe to a topic.
topic The topic to subscribe to
void ESPMegaIoT::unsubscribeFromTopic(char *topic)
Unsubscribe from a topic.
topic The topic to unsubscribe from
void ESPMegaIoT::connectToWifi(char *ssid, char *password)
Connect to a wifi network.
ssid The SSID of the wifi network password The password of the wifi network
Referenced by connectNetwork.
void ESPMegaIoT::connectToWifi(char *ssid)
Connect to a unsecured wifi network.
ssid The SSID of the wifi network
void ESPMegaIoT::disconnectFromWifi()
Disconnect from the wifi network.
bool ESPMegaIoT::wifiConnected()
Check if the wifi is connected.
True if the wifi is connected, false otherwise
void ESPMegaIoT::ethernetBegin()
Begin the ethernet interface.
References NetworkConfig::hostname.
Referenced by connectNetwork.
void ESPMegaIoT::loadNetworkConfig()
Load the network config from FRAM.
References NetworkConfig::dns1, NetworkConfig::dns2, NetworkConfig::gateway, NetworkConfig::hostname, NetworkConfig::ip, NetworkConfig::password, NetworkConfig::ssid, NetworkConfig::subnet, NetworkConfig::useStaticIp, NetworkConfig::useWifi, NetworkConfig::wifiUseAuth.
void ESPMegaIoT::saveNetworkConfig()
Save the network config to FRAM.
References NetworkConfig::dns1, NetworkConfig::dns2, NetworkConfig::gateway, NetworkConfig::hostname, NetworkConfig::ip, NetworkConfig::password, NetworkConfig::ssid, NetworkConfig::subnet, NetworkConfig::useStaticIp, NetworkConfig::useWifi, NetworkConfig::wifiUseAuth.
NetworkConfig * ESPMegaIoT::getNetworkConfig()
Get the network config.
You should not modify the returned struct directly The network config struct
Referenced by InternalDisplay::begin.
MqttConfig * ESPMegaIoT::getMqttConfig()
Get the MQTT config.
You should not modify the returned struct directly The MQTT config struct
Referenced by InternalDisplay::begin.
void ESPMegaIoT::setMqttConfig(MqttConfig mqtt_config)
Set the MQTT config.
mqtt_config The MQTT config struct
References MqttConfig::base_topic.
void ESPMegaIoT::saveMqttConfig()
Save the MQTT config to FRAM.
References MqttConfig::base_topic, MqttConfig::mqtt_password, MqttConfig::mqtt_port, MqttConfig::mqtt_server, MqttConfig::mqtt_useauth, MqttConfig::mqtt_user.
void ESPMegaIoT::loadMqttConfig()
Load the MQTT config from FRAM.
References MqttConfig::base_topic, MqttConfig::mqtt_password, MqttConfig::mqtt_port, MqttConfig::mqtt_server, MqttConfig::mqtt_useauth, MqttConfig::mqtt_user.
void ESPMegaIoT::connectNetwork()
Connect to the network using the current config.
References connectToWifi, NetworkConfig::dns1, NetworkConfig::dns2, ethernetBegin, NetworkConfig::gateway, NetworkConfig::ip, NetworkConfig::password, NetworkConfig::ssid, NetworkConfig::subnet, NetworkConfig::useStaticIp, NetworkConfig::useWifi, NetworkConfig::wifiUseAuth.
void ESPMegaIoT::setNetworkConfig(NetworkConfig network_config)
Set the network config.
network_config The network config struct
void ESPMegaIoT::connectToMqtt()
Connect to MQTT with the current config.
References NetworkConfig::hostname, MqttConfig::mqtt_password, MqttConfig::mqtt_port, MqttConfig::mqtt_server, MqttConfig::mqtt_useauth, MqttConfig::mqtt_user.
bool ESPMegaIoT::connectToMqtt(char *client_id, char *mqtt_server, uint16_t mqtt_port, char *mqtt_user, char *mqtt_password)
Connect to a MQTT broker with authentication.
client_id The client id to use mqtt_server The MQTT server to connect to mqtt_port The MQTT port to connect to mqtt_user The MQTT username to use mqtt_password The MQTT password to use True if the connection is successful, false otherwise
bool ESPMegaIoT::connectToMqtt(char *client_id, char *mqtt_server, uint16_t mqtt_port)
Connect to a MQTT broker without authentication.
client_id The client id to use mqtt_server The MQTT server to connect to mqtt_port The MQTT port to connect to True if the connection is successful, false otherwise
bool ESPMegaIoT::mqttConnected()
Check if the MQTT is connected.
True if the MQTT is connected, false otherwise
void ESPMegaIoT::disconnectFromMqtt()
Disconnect from the MQTT broker.
void ESPMegaIoT::publish(const char *topic, const char *payload)
Publish a message to a topic.
topic The topic to publish to payload The payload to publish
uint8_t ESPMegaIoT::registerMqttCallback(std::function< void(char *, char *)> callback)
Register a callback for MQTT messages.
callback The callback function The handler for the callback
void ESPMegaIoT::unregisterMqttCallback(uint8_t handler)
Unregister a callback.
handler The handler of the callback
uint8_t ESPMegaIoT::registerRelativeMqttCallback(std::function< void(char *, char *)> callback)
Register a callback for MQTT messages relative to the base topic.
The message's base topic will be removed before calling the callback callback The callback function The handler for the callback
void ESPMegaIoT::unregisterRelativeMqttCallback(uint8_t handler)
Unregister a relative MQTT callback.
handler The handler of the callback
uint8_t ESPMegaIoT::registerSubscribeCallback(std::function< void(void)> callback)
Register a function to be called when the ESPMegaIoT object is subscribing to topics.
callback The callback function The handler for the callback
void ESPMegaIoT::unregisterSubscribeCallback(uint8_t handler)
Unregister a subscribe callback.
handler The handler of the callback
void ESPMegaIoT::setBaseTopic(char *base_topic)
Set the base topic for the IoT.
base_topic The base topic
References MqttConfig::base_topic.
void ESPMegaIoT::bindEthernetInterface(ETHClass *ethernetIface)
Bind an ethernet interface to the ESPMegaIoT object.
ethernetIface The ethernet interface to bind (ETH for ESPMegaPRO R3)
bool ESPMegaIoT::networkConnected()
Check if the network is connected.
True if the network is connected, false otherwise
References NetworkConfig::useWifi.
Referenced by InternalDisplay::loop.
void ESPMegaIoT::bindFRAM(FRAM *fram)
Bind a FRAM object to the ESPMegaIoT object.
This class is hardcode to use the FRAM address 34-300 fram The FRAM object to bind
Referenced by ESPMegaPRO::enableIotModule.
IoTComponent * ESPMegaIoT::getComponent(uint8_t card_id)
Get the IoTComponent object for a card.
card_id The id of the card The IoTComponent object for the card
IPAddress ESPMegaIoT::getETHIp()
Get the Ethernet IP Address.
The Ethernet IP Address
Referenced by getIp.
IPAddress ESPMegaIoT::getWifiIp()
Get the Wifi IP address.
The Wifi IP address
Referenced by getIp.
IPAddress ESPMegaIoT::getIp()
Get the IP address of the currently active network interface.
The IP address of the currently active network interface
References getETHIp, getWifiIp, NetworkConfig::useWifi.
String ESPMegaIoT::getETHMac()
Get the MAC Address of the Ethernet interface.
The MAC Address of the Ethernet interface
Referenced by getMac.
String ESPMegaIoT::getWifiMac()
Get the MAC Address of the Wifi interface.
The MAC Address of the Wifi interface
Referenced by getMac.
String ESPMegaIoT::getMac()
Get the MAC Address of the currently active network interface.
The MAC Address of the currently active network interface
References getETHMac, getWifiMac, NetworkConfig::useWifi.
void ESPMegaIoT::sessionKeepAlive()
Keep the MQTT session alive.
This function is called automatically by the ESPMegaIoT object, You should not call this function directly
bool ESPMegaIoT::mqttReconnect()
Subscribe relative to the base topic.
void ESPMegaIoT::wifiReconnect()
void ESPMegaIoT::mqttSubscribe()
Subscribe to all components's topics.
void ESPMegaIoT::mqttCallback(char *topic, byte *payload, unsigned int length)
The mqtt callback function, This function is called when a message is received on a subscribed topic.
This function is called when a message is received on a subscribed topic The payload is copied to a buffer and a null terminator is added The payload is then passed to the respective card's mqtt callback topic The topic of the message payload The payload of the message in byte form length The length of the payload
void ESPMegaIoT::publishRelative(uint8_t card_id, char *topic, char *payload)
Publish relative to the base topic.