AnalogIoT
uint8_t AnalogIoT::adc_conversion_callback_index
uint8_t AnalogIoT::dac_set_state_length
uint8_t AnalogIoT::dac_set_value_length
uint8_t AnalogIoT::dac_state_length
uint8_t AnalogIoT::dac_value_length
uint8_t AnalogIoT::request_state_length
uint8_t AnalogIoT::dac_publish_enable_length
uint32_t AnalogIoT::last_adc_publish
AnalogCard* AnalogIoT::card
bool AnalogIoT::adc_publish_enabled[8][8]
uint16_t AnalogIoT::adc_conversion_interval[8][8]
uint32_t AnalogIoT::last_adc_conversion[8][8]
std::map<uint8_t, std::function<void(uint8_t, uint16_t)> > AnalogIoT::adc_conversion_callbacks
AnalogIoT::AnalogIoT()
Default constructor for the AnalogIoT class.
This constructor initializes the AnalogIoT object and sets up the ADC conversion callbacks.
AnalogIoT::~AnalogIoT()
Default destructor for the AnalogIoT class.
bool AnalogIoT::begin(uint8_t card_id, ExpansionCard *card, PubSubClient *mqtt, char *base_topic)
Initializes the AnalogIoT object.
card_id The ID of the card. card A pointer to the card object. mqtt A pointer to the MQTT client object. base_topic The base MQTT topic. True if the initialization was successful, false otherwise. This function can be called from the main program but it is recommended to use ESPMegaIoT to initialize the IoT Components. This function initializes the AnalogIoT object and registers the callbacks for handling DAC changes.
References handleDACChange.
void AnalogIoT::handleMqttMessage(char *topic, char *payload)
Publishes the state of all DACs.
This function is called when a request state message is received.
References processADCSetConversionEnabledMessage, processADCSetConversionIntervalMessage, processDACSetStateMessage, processDACSetValueMessage, processRequestStateMessage.
void AnalogIoT::handleDACChange(uint8_t pin, uint16_t value)
Publishes the state of a DAC.
pin The pin of the DAC.
References publishDAC.
Referenced by begin.
void AnalogIoT::publishADCs()
Publishes the state of all DACs.
References publishADC.
Referenced by processRequestStateMessage, publishReport.
void AnalogIoT::publishADC(uint8_t pin)
Publishes the state of a DAC.
pin The pin of the DAC.
References AnalogCard::analogRead.
Referenced by publishADCs.
void AnalogIoT::publishDACs()
Publishes the state of all DACs.
References publishDAC.
Referenced by processRequestStateMessage, publishReport.
void AnalogIoT::publishDAC(uint8_t pin)
Publishes the state of a DAC.
pin The pin of the DAC.
References publishDACState, publishDACValue.
Referenced by handleDACChange, publishDACs.
void AnalogIoT::publishDACState(uint8_t pin)
Publishes the state of a DAC.
pin The pin of the DAC.
References AnalogCard::getDACState.
Referenced by publishDAC.
void AnalogIoT::publishDACValue(uint8_t pin)
Publishes the value of a DAC.
pin The pin of the DAC.
References AnalogCard::getDACValue.
Referenced by publishDAC.
void AnalogIoT::setADCsPublishInterval(uint32_t interval)
Sets the interval at which the state of all DACs is published.
interval The interval in milliseconds.
void AnalogIoT::setADCsPublishEnabled(bool enabled)
Sets whether the state of all DACs is published.
enabled True if the state of all DACs should be published, false otherwise.
uint8_t AnalogIoT::registerADCConversionCallback(std::function< void(uint8_t, uint16_t)> callback)
Registers a callback for handling ADC conversions.
callback The callback function. The handler of the callback.
void AnalogIoT::unregisterADCConversionCallback(uint8_t handler)
Unregisters a callback for handling ADC conversions.
handler The handler of the callback.
void AnalogIoT::setADCConversionInterval(uint8_t pin, uint16_t interval)
Sets the interval at which the value of an ADC channel is read.
pin The pin of the ADC channel. interval The interval in milliseconds.
Referenced by processADCSetConversionIntervalMessage.
void AnalogIoT::setADCConversionEnabled(uint8_t pin, bool enabled)
Enables or disables the periodic reading of the value of an ADC channel.
pin The pin of the ADC channel. enabled True if the value of the ADC channel should be read, false otherwise.
Referenced by processADCSetConversionEnabledMessage.
bool AnalogIoT::processADCSetConversionIntervalMessage(char *topic, char *payload, uint8_t topic_length)
Processes a message received on the MQTT topic for setting the state of a DAC.
topic The topic of the message. payload The payload of the message. topic_length The length of the topic. This function is not meant to be called from user code. True if the message was processed, false otherwise.
References setADCConversionInterval.
Referenced by handleMqttMessage.
bool AnalogIoT::processADCSetConversionEnabledMessage(char *topic, char *payload, uint8_t topic_length)
Processes a message received on the MQTT topic for setting the value of a DAC.
topic The topic of the message. payload The payload of the message. topic_length The length of the topic. This function is not meant to be called from user code. True if the message was processed, false otherwise.
References setADCConversionEnabled.
Referenced by handleMqttMessage.
bool AnalogIoT::processDACSetStateMessage(char *topic, char *payload, uint8_t topic_length)
Processes a message received on the MQTT topic for setting the state of a DAC.
topic The topic of the message. payload The payload of the message. topic_length The length of the topic. This function is not meant to be called from user code. True if the message was processed, false otherwise.
References AnalogCard::setDACState.
Referenced by handleMqttMessage.
bool AnalogIoT::processDACSetValueMessage(char *topic, char *payload, uint8_t topic_length)
Processes a message received on the MQTT topic for setting the value of a DAC.
topic The topic of the message. payload The payload of the message. topic_length The length of the topic. This function is not meant to be called from user code. True if the message was processed, false otherwise.
References AnalogCard::setDACValue.
Referenced by handleMqttMessage.
bool AnalogIoT::processRequestStateMessage(char *topic, char *payload, uint8_t topic_length)
Processes a message received on the MQTT topic for requesting the state of all DACs.
topic The topic of the message. payload The payload of the message. topic_length The length of the topic. This function is not meant to be called from user code. True if the message was processed, false otherwise.
References publishADCs, publishDACs.
Referenced by handleMqttMessage.
void AnalogIoT::publishReport()
Publishes the state of all DACs.
References publishADCs, publishDACs.
void AnalogIoT::subscribe()
Subscribes to all MQTT topics used by the AnalogIoT object.
This function is called when the MQTT client connects.
void AnalogIoT::loop()
uint8_t AnalogIoT::getType()
Gets the type of the card.
The type of the card.