DigitalInputIoT
bool DigitalInputIoT::digital_inputs_publish_enabled
DigitalInputCard* DigitalInputIoT::card
bool DigitalInputIoT::begin(uint8_t card_id, ExpansionCard *card, PubSubClient *mqtt, char *base_topic)
Initializes the DigitalInputIoT object.
This function sets the necessary parameters for the DigitalInputIoT object, such as the card ID, expansion card, MQTT client, and base topic. It also enables the publishing of digital input values and registers a callback function for handling value changes. Although this function can be called in the main program, it is recommended to use ESPMegaIoT::registerCard() to automatically manage the instantiation and initialization of this component. card_id The ID of the card. card Pointer to the DigitalInputCard object. mqtt Pointer to the PubSubClient object. base_topic The base topic for MQTT communication. True if the initialization is successful, false otherwise.
References handleValueChange, setDigitalInputsPublishEnabled.
void DigitalInputIoT::handleMqttMessage(char *topic, char *payload)
Handles MQTT messages for the DigitalInputIoT component.
topic The trimmed topic of the MQTT message. payload The null-terminated payload of the MQTT message.
References setDigitalInputsPublishEnabled.
void DigitalInputIoT::publishDigitalInputs()
Publish all digital inputs to the MQTT broker.
References publishDigitalInput.
Referenced by publishReport, setDigitalInputsPublishEnabled.
void DigitalInputIoT::publishDigitalInput(uint8_t pin)
Publish a digital input to the MQTT broker.
pin The pin to publish.
References DigitalInputCard::digitalRead.
Referenced by handleValueChange, publishDigitalInputs.
void DigitalInputIoT::setDigitalInputsPublishEnabled(bool enabled)
Set if the digital inputs should be published to the MQTT broker.
enabled True if the digital inputs should be published, false otherwise.
References publishDigitalInputs.
Referenced by begin, handleMqttMessage.
void DigitalInputIoT::handleValueChange(uint8_t pin, uint8_t value)
Handles a value change for a digital input.
This function is registered as a callback function for the DigitalInputCard object. pin The pin that changed. value The new value of the pin.
References publishDigitalInput.
Referenced by begin.
void DigitalInputIoT::publishReport()
Publish all inputs to the MQTT Broker.
This function is overriden from the IoTComponent class and is called by ESPMegaIoT. pin The pin to publish.
References publishDigitalInputs.
void DigitalInputIoT::subscribe()
Subscribes to the MQTT topics for the DigitalInputIoT component.
uint8_t DigitalInputIoT::getType()