AnalogCard
uint8_t AnalogCard::handler_count
std::map<uint8_t, std::function<void(uint8_t, bool, uint16_t)> > AnalogCard::dac_change_callbacks
bool AnalogCard::dac_state[4][4]
uint16_t AnalogCard::dac_value[4][4]
MCP4725 AnalogCard::dac0
MCP4725 AnalogCard::dac1
MCP4725 AnalogCard::dac2
MCP4725 AnalogCard::dac3
Adafruit_ADS1115 AnalogCard::analogInputBankA
Adafruit_ADS1115 AnalogCard::analogInputBankB
AnalogCard::AnalogCard()
Default constructor for the AnalogCard class.
void AnalogCard::dacWrite(uint8_t pin, uint16_t value)
Writes a value to the specified DAC pin.
pin The DAC pin to write to. value The value to write.
References setDACState, setDACValue.
void AnalogCard::sendDataToDAC(uint8_t pin, uint16_t value)
Sends data to the specified DAC pin.
pin The DAC pin to send data to. value The data to send. This function does not call the DAC change callbacks.
Referenced by setDACState, setDACValue.
uint16_t AnalogCard::analogRead(uint8_t pin)
Reads the value from the specified analog pin.
pin The analog pin to read from. The value read from the analog pin.
Referenced by AnalogIoT::publishADC.
bool AnalogCard::begin()
Initializes the AnalogCard.
True if initialization is successful, false otherwise.
void AnalogCard::loop()
The main loop of the AnalogCard.
This function does nothing.
bool AnalogCard::getDACState(uint8_t pin)
Gets the state of the specified DAC pin.
pin The DAC pin to get the state of. The state of the DAC pin (true = on, false = off).
Referenced by AnalogIoT::publishDACState.
uint16_t AnalogCard::getDACValue(uint8_t pin)
Gets the value of the specified DAC pin.
pin The DAC pin to get the value of. The value of the DAC pin.
Referenced by AnalogIoT::publishDACValue.
void AnalogCard::setDACState(uint8_t pin, bool state)
Sets the state of the specified DAC pin.
pin The DAC pin to set the state of. state The state to set (true = on, false = off).
References sendDataToDAC.
Referenced by dacWrite, AnalogIoT::processDACSetStateMessage.
void AnalogCard::setDACValue(uint8_t pin, uint16_t value)
Sets the value of the specified DAC pin.
pin The DAC pin to set the value of. value The value to set.
References sendDataToDAC.
Referenced by dacWrite, AnalogIoT::processDACSetValueMessage.
uint8_t AnalogCard::registerDACChangeCallback(std::function< void(uint8_t, bool, uint16_t)> callback)
Registers a callback function to be called when the state or value of a DAC pin changes.
callback The callback function to register. The handler ID of the registered callback.
void AnalogCard::unregisterDACChangeCallback(uint8_t handler)
Unregisters a previously registered DAC change callback.
handler The handler ID of the callback to unregister.
uint8_t AnalogCard::getType()
Gets the type of the AnalogCard.
The type of the AnalogCard.