.TH "/home/siwat/ESPMegaPRO3-library/AnalogIoT.cpp" 3 "Tue Jan 9 2024" "ESPMega PRO R3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/siwat/ESPMegaPRO3-library/AnalogIoT.cpp \- Implementation of the \fBAnalogIoT\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <AnalogIoT\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the \fBAnalogIoT\fP class\&. 

This file contains the implementation of the \fBAnalogIoT\fP class, which provides functionality for handling analog input and output operations in an IoT system\&. The class allows for setting the state and value of digital-to-analog converters (DACs), as well as reading the value of analog-to-digital converters (ADCs)\&. It also supports publishing the state and value of DACs and ADCs over MQTT\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ESPMega PRO R3 from the source code\&.
