.TH "/home/siwat/ESPMegaPRO3-library/AnalogCard.cpp" 3 "Tue Jan 9 2024" "ESPMega PRO R3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/siwat/ESPMegaPRO3-library/AnalogCard.cpp \- Implementation of the \fBAnalogCard\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <AnalogCard\&.hpp>\fP
.br
\fC#include 'esp_log\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the \fBAnalogCard\fP class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for ESPMega PRO R3 from the source code\&.
