.TH "ClimateCardData" 3 "Tue Jan 9 2024" "ESPMega PRO R3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClimateCardData \- The struct is used to store the state of the air conditioner\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClimateCard\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBac_temperature\fP"
.br
.RI "Temperature of the air conditioner\&. "
.ti -1c
.RI "uint8_t \fBac_mode\fP"
.br
.RI "Mode of the air conditioner\&. "
.ti -1c
.RI "uint8_t \fBac_fan_speed\fP"
.br
.RI "Fan speed of the air conditioner\&. "
.in -1c
.SH "Detailed Description"
.PP 
The struct is used to store the state of the air conditioner\&. 


.PP
\fBNote\fP
.RS 4
This struct is stored in FRAM if it is used 
.PP
This struct is 3 bytes long 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ESPMega PRO R3 from the source code\&.
