.TH "/home/siwat/ESPMegaPRO3-library/ClimateCard.cpp" 3 "Tue Jan 9 2024" "ESPMega PRO R3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/siwat/ESPMegaPRO3-library/ClimateCard.cpp \- Implementation file for the \fBClimateCard\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ClimateCard\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 
Implementation file for the \fBClimateCard\fP class\&. 

This file contains the implementation of the \fBClimateCard\fP class, which represents a climate control card\&. The \fBClimateCard\fP class provides methods for controlling an air conditioner, reading temperature and humidity from sensors, and saving and loading the state to/from FRAM memory\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ESPMega PRO R3 from the source code\&.
