.TH "/home/siwat/ESPMegaPRO3-library/ESPMegaWebServer.cpp" 3 "Tue Jan 9 2024" "ESPMega PRO R3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/siwat/ESPMegaPRO3-library/ESPMegaWebServer.cpp \- Implementation file for the \fBESPMegaWebServer\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ESPMegaWebServer\&.hpp>\fP
.br

.SH "Detailed Description"
.PP 
Implementation file for the \fBESPMegaWebServer\fP class\&. 

This file contains the implementation of the \fBESPMegaWebServer\fP class, which is responsible for handling web server functionality for the \fBESPMegaPRO\fP firmware\&. The \fBESPMegaWebServer\fP class provides methods for starting the web server, handling HTTP requests, and managing credentials and configurations\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ESPMega PRO R3 from the source code\&.
